addons:
    postgresql: "9.4.1"
language: ruby
rvm:
  - 2.0.0
before_script:
  - cp config/database.yml.travis config/database.yml
script: 
  - bundle exec rake db:create
  - bundle exec rake db:migrate --trace
  - bundle exec rake db:test:prepare
  - bundle exec rake db:seed
  - bundle exec rake 
