development:
  adapter: postgresql
  encoding: unicode
  database: magic_development
  pool: 5

test:
  adapter: postgresql
  encoding: unicode
  database: magic_test
  pool: 5

production:
  adapter: postgresql
  encoding: unicode
  database: magic_production
  pool: 5
