development:
  adapter: postgresql
  encoding: unicode
  database: magic_development
  pool: 5
  username: 
  password:

test:
  adapter: postgresql
  encoding: unicode
  database: magic_test
  pool: 5
  username: 
  password:
  host: localhost

production:
  adapter: postgresql
  encoding: unicode
  database: magic_production
  pool: 5
