defaults: &defaults
  encoding: unicode
  pool: 5

development:
  <<: *defaults
  database: magic_development

test:
  <<: *defaults
  database: magic_test

production:
  <<: *defaults
  database: magic_production
